// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcjmZ6prPLHknHqkt4M_I9CJD3frrmnRA',
    appId: '1:174631897882:web:d38a7f16e7a7811c063aa3',
    messagingSenderId: '174631897882',
    projectId: 'bikershaven-a8289',
    authDomain: 'bikershaven-a8289.firebaseapp.com',
    storageBucket: 'bikershaven-a8289.appspot.com',
    measurementId: 'G-JFRL2X622E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTBZPJEaO2dccApUetXc4_YJksV_4nwHg',
    appId: '1:174631897882:android:287ce2c11a767252063aa3',
    messagingSenderId: '174631897882',
    projectId: 'bikershaven-a8289',
    storageBucket: 'bikershaven-a8289.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsqSF102mmHkCqWAdxYk8uIR6zONG-GxI',
    appId: '1:174631897882:ios:7f8d604bafd359e5063aa3',
    messagingSenderId: '174631897882',
    projectId: 'bikershaven-a8289',
    storageBucket: 'bikershaven-a8289.appspot.com',
    iosBundleId: 'com.example.mapbox2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsqSF102mmHkCqWAdxYk8uIR6zONG-GxI',
    appId: '1:174631897882:ios:177f2766dd481b77063aa3',
    messagingSenderId: '174631897882',
    projectId: 'bikershaven-a8289',
    storageBucket: 'bikershaven-a8289.appspot.com',
    iosBundleId: 'com.example.mapbox2.RunnerTests',
  );
}
